# Generated by Django 5.2.7 on 2025-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_personaje_x_personaje_y_alter_personaje_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('martriz', models.CharField(max_length=5000)),
            ],
        ),
    ]
