# Generated by Django 5.2.7 on 2025-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_imagenfondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('direccion', models.CharField(max_length=1)),
                ('color', models.CharField(default='0,0,0', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagenfondo',
            name='martriz',
        ),
    ]
