# Generated by Django 5.2.7 on 2025-11-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_pared_remove_imagenfondo_martriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenfondo',
            name='paredes',
            field=models.ManyToManyField(to='backend.pared'),
        ),
    ]
