# Generated by Django 5.2.7 on 2025-11-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_imagenfondo_paredes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pared',
            old_name='x',
            new_name='x1',
        ),
        migrations.RenameField(
            model_name='pared',
            old_name='y',
            new_name='y1',
        ),
    ]
