# Generated by Django 5.2.7 on 2025-11-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_x_pared_x1_rename_y_pared_y1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pared',
            old_name='x1',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='pared',
            old_name='y1',
            new_name='y',
        ),
    ]
